Add Documentation for Support
GoogleCloudPlatform/cloud-code-vscode pull request #271
Opened 2020-07-26 21:32 UTC by sivakku

- Adding ways for external users to support/report the issues to our team.

2020-07-27 18:47 UTC, sanguinecloud commented on README.md
> +- To report an issue, first create a stack overflow issue and add the two tags [google-cloud-platform][cloud-code] and post the link for it in the above slack channel.
With edits:

## Support

- To get support on issues you might encounter, join our Slack channel [cloud-code-ide](https://googlecloud-community.slack.com/messages/cloud-code-ide) for Cloud Code support.
- To report an issue, create a Stack Overflow question, add the two tags, [google-cloud-platform] and [cloud-code] to your question, and post a link to it in our Slack channel.

2020-07-27 23:21 UTC, sivakku commented on README.md
> +- To report an issue, first create a stack overflow issue and add the two tags [google-cloud-platform][cloud-code] and post the link for it in the above slack channel.
Updated. What other landing pages do you see to be added for users to join the slack channel?

2020-07-27 23:41 UTC, kschaab commented on README.md
> +- To report an issue, first create a stack overflow issue and add the two tags [google-cloud-platform][cloud-code] and post the link for it in the above slack channel.
I don't totally get this, why are we raising these above open an issue in VS Code and the issue tracker on github?  Those should be our default options rather than things that we don't actively monitor ATM.

2020-07-27 23:50 UTC, sivakku commented on README.md
> +- To report an issue, first create a stack overflow issue and add the two tags [google-cloud-platform][cloud-code] and post the link for it in the above slack channel.
i should probably add that to clarify the support, github issues are the way to report bugs or feature tasks, anything that is not a bug/task but need more input driving from community or integrations. SO would give a search index since slack would loose the history if it is not an enterprise edition and doesn't provide good way to organize community answers.

2020-07-27 23:57 UTC, sivakku commented on README.md
> +- To report an issue, first create a stack overflow issue and add the two tags [google-cloud-platform][cloud-code] and post the link for it in the above slack channel.
Updated.
The SO is questions for cloud code users community driven by cloud code users. 
The github is for product bugs or product asks.

2020-07-29 17:46 UTC, russwolf commented on README.md
> +- To report any bug or task on the product, continue to use github issues, which will be triaged internally and updated.
"github" should be "GitHub"

2020-07-29 17:47 UTC, russwolf commented on README.md
> +- To report any bug or task on the product, continue to use github issues, which will be triaged internally and updated.
instead of "task", I'd say "feature request" or "to make a feature request"

2020-07-29 17:48 UTC, russwolf commented on README.md
> +- Join our community of users using Slack channel [cloud-code-ide](https://googlecloud-community.slack.com/messages/cloud-code-ide) for Cloud Code support and outreach.
So is this going to be a single Slack channel for support for all things Cloud Code IDE related and not VS Code specific? Is the IntelliJ team bought into this?

2020-07-29 17:49 UTC, russwolf commented on README.md
> +- If you are not sure of it is either a bug or product ask, to reach out to cloud code users community, create a Stack Overflow question, and add the two tags [google-cloud-platform] and [cloud-code]
When users are looking for solutions, is it easier for them to look for Cloud Code solutions or is it easier to look for Cloud Code for IntelliJ vs. Cloud Code for VS Code solutions? What is the thought process behind a single tag vs. two different tags vs. multiple tags here on StackOverflow?

2020-07-29 17:50 UTC, russwolf commented on README.md
> +## Support
Are these the official support channels for Cloud Code or is Google Cloud Support the official support channel for Google Cloud customers? When should I use these vs. Google Cloud support if I am an Enterprise?

2020-11-10 22:32 UTC, kschaab requested changes
This has changed a lot since we have a new slack channel

2020-11-20 01:43 UTC, sivakku commented
Abandoning this pull request since this is distributed in a different format.

2020-11-20 01:43 UTC, closed without merging