Create SECURITY.md
GoogleCloudPlatform/cloud-code-vscode pull request #447
Opened 2021-07-06 18:41 UTC by briandealwis

Define our security vulnerability procedure, using OSPO's recommended intake through `g.co/vulnz`.

2021-07-07 17:05 UTC, ssmall requested changes
It doesn't appear that `SECURITY.md` actually got added to this PR. Do you need to `git add` it?

2021-07-07 20:45 UTC, briandealwis commented
:blush:

2021-07-07 21:24 UTC, ssmall approved these changes

2021-07-13 19:32 UTC, kschaab approved these changes

2021-07-14 14:26 UTC, merged